[package]
name = "my_lean_project"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cd7f0626a0b04be1dda223a26123313514a55fb4"}
